version: '3.9'
services:

  frontend:
    build: ./python
    restart: always
    ports:
      - "80:5000"
    depends_on:
      - backend

  backend:
    build: ./golang
    restart: always
  #   depends_on:
  #   - database 

  # database:
  #   image: postgres:latest
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: ToDoList