version: '3.9'
services:

  frontend:
    build: ./python
    restart: always
    depends_on:
    - backend 

  backend:
    build: ./golang
    restart: always
    depends_on:
    - pg 

  pg:
    image: postgres:latest
    restart: always