{{- range .Values.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .name }}-deployment
  template:
    metadata:
      labels:
        app: {{ .name }}-deployment
    spec:
      containers:
      - name: {{ .name }}-deployment
        image: "{{ .image.repository }}:{{ .image.tag }}"
{{- if .env }}
        env:
        {{- range $key, $val := .env }}
        - name: {{ $key | quote }}
          value: {{ $val | quote }}
        {{- end }}
{{- end }}
        resources:
{{ toYaml .resources | indent 10 }}
        ports:
        - containerPort: {{ .port }}
{{- if .volumeMounts }}
        volumeMounts:
        {{- range .volumeMounts }}
        - name: {{ .name | quote }}
          mountPath: {{ .mountPath | quote }}
        {{- end }}
{{- end }}
      volumes:
{{- if .volumes }}
      {{- range .volumes }}
      - name: {{ .name | quote }}
        {{- if .persistentVolumeClaim }}
        persistentVolumeClaim:
          claimName: {{ .persistentVolumeClaim.claimName | quote }}
        {{- else if .emptyDir }}
        emptyDir: {}
        {{- else if .hostPath }}
        hostPath:
          path: {{ .hostPath.path | quote }}
        {{- end }}
      {{- end }}
{{- end }}
{{- end }}
