{{- range .Values.deployments }}
{{- if ne .name "database" }}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .name }}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .kind | default "Deployment" }}
    name: "{{ .name }}-{{ .kind | default "Deployment" }}"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
{{- end }}
{{- end }}
