{{- range .Values.deployments }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  type: {{ .service }}
  selector:
    app: {{ .name }}-deployment
  ports:
  - port: {{ .extport }}
    targetPort: {{ .port }}
{{- end }}